In [5]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression # 선형 회귀 분석 모델
from sklearn.metrics import mean_squared_error, r2_score # 수학공식 모아둔 패키지


from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix, roc_curve, roc_auc_score
import pandas as pd
from sklearn.metrics import classification_report


from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [14]:
iris = load_iris()

In [15]:
X = iris.data
y = iris.target

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
model = LogisticRegression(multi_class = 'ovr')
# ovr  : one vs rest

In [18]:
model.fit(X_train, y_train)

/opt/anaconda3/envs/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'ovr'


In [21]:
y_test[15]

np.int64(1)

In [22]:
y_pred = model.predict(X_test)
y_pred[15]

np.int64(2)

In [23]:
y_proba = model.predict_proba(X_test) 
y_proba[15]

array([0.00883226, 0.44332253, 0.54784521])

In [24]:
# 0이 될 확률, 1이 될 확률 (0.4) , 2가 될 확률(0.5)임
# 실제 test값은 1 pred값은 2 으로 : 1이 될 확률이 낮게 나오는건 아님

In [25]:
accuracy_score(y_test, y_pred) # 정확도

0.9666666666666667

In [28]:
precision_score(y_test, y_pred, average=None) # 정밀도

array([1.        , 1.        , 0.91666667])

In [29]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0,  8,  1],
       [ 0,  0, 11]])

In [ ]:
recall_score(y_test, y_pred) # 재현률

In [32]:
f1_score(y_test, y_pred)  # Precision과 Recall의 조화평균

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [33]:
roc_auc_score(y_test, y_proba,multi_class='ovr')

1.0

In [51]:
df = sns.load_dataset('titanic')

In [52]:
df['age'].fillna(df.groupby(['sex','class'])['age'].transform('mean'))

/var/folders/7d/4294lrxx67jdcn0_3qst6jf00000gn/T/ipykernel_8521/4241832749.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['age'].fillna(df.groupby(['sex','class'])['age'].transform('mean'))


0      22.00
1      38.00
2      26.00
3      35.00
4      35.00
       ...  
886    27.00
887    19.00
888    21.75
889    26.00
890    32.00
Name: age, Length: 891, dtype: float64

In [53]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [57]:
df['deck'].fillna("Unknown", inplace=True )

/var/folders/7d/4294lrxx67jdcn0_3qst6jf00000gn/T/ipykernel_8521/1965231912.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['deck'].fillna("Unknown", inplace=True )


In [56]:
df['deck'] = pd.Categorical(df['deck'], categories=['A','B','C','D','E','F','G','Unknown'])

In [58]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck             0
embark_town      2
alive            0
alone            0
dtype: int64

In [60]:
df_t = df[['pclass','who','age','sibsp','parch','fare','embarked','deck']]

In [62]:
df_t['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [ ]:
df_t['embarked'] = df_t['embarked']

In [64]:
from sklearn.preprocessing import LabelEncoder